@startuml
'https://plantuml.com/class-diagram


class AppClientHttpClient {
    - client: HttpClient
    + fetchForAvailableCars() : List<Car>
    + requestCarSession(String) : String
    + getWebSocketUrl() : String
    + getHttpClient() : HttpClient
}

@enduml