@startuml
'https://plantuml.com/class-diagram

class CarApplication
{
+ run()
- registerCar() : Result
- unregisterCar() : Result
- onCarLocked() : Unit
- onCarUnlocked() : Unit
- mVuid : String
- mHttpClient : HttpClient
}

class HttpClient

CarApplication --> HttpClient
@enduml