@startuml
'https://plantuml.com/class-diagram

object CarApplication {
    + main() : Unit
}

class CarClient
{
+ registerCar() : HttpStatusCode
+ unregisterCar() : HttpStatusCode
+ updateCarStatus() : HttpStatusCode
+ getCarStatus() : Car
+ getHttpClient() : HttpClient
- carStatus : Car
- httpClient : HttpClient
}

class HttpClient

CarClient --> HttpClient
CarApplication --> CarClient

@enduml