@startuml

Car -> Server: Register
alt if Car Registered
Server --> Car: Return Error
else
Server --> Car: Return Car Public Key
end

loop Car Update Sequence
Car --> Server : Start Status Update Routine
end

alt Car Unregisters
Car -> Server : Notify Unregister
Server -> Server : Delete Car Private Key
Server --> Car : Acknowledge Unregister
Car -> Car: Delete Car Public Key
end
@enduml
