@startuml
Client -> Server : Request Session with VUID

alt Cannot Request Session
    Server -> Client : Respond Not Ok
else
    Server -> Client : Respond With Car JWT
end
Client -> Car: Requests Session With JWT
Car -> Car: Validates JWT Signature Against Public Key

alt Signature Is Valid
    Car -> Client : Allow Session With Client
    Car -> Server : Update unavailability
else
    Car -> Client : Close WebSocket
end

group Car Session With Client
   Client -> Car : Request To Unlock Door
   alt if Car Door Is Locked
        Car -> Car : Unlock Door
        Car -> Client : Respond With Success
   else
        Car -> Client : Respond With Error Message
   end
  Client -> Car : Request To Lock Door
  alt if Car Door Is Unlocked
       Car -> Car : Lock Door
       Car -> Client : Respond With Success
  else
       Car -> Client : Respond With Error Message
  end

  alt if Client Request End Session
    Client -> Car : Request End Session
    Car -> Client : Send End Session With Report
    Car -> Car: End WebSocket
    Server -> Client : Send Session Report
  end
end

@enduml
