@startuml

Client -> Server : Request Session with VUID

alt Cannot Request Session
    Server -> Client : Respond Not Ok
else
    Server -> Client : Respond With Car JWT
end

loop UserCar Session WebSocket

group Car Session With Client
   Client -> Car : Request To Car With JWT
   Car -> Car :  Validate JWT signature against public key
   alt signature is invalid
    Car -> Client : Respond Not Ok
   else
    Car -> Client : Respond To Request
   end
   alt Client Ends Session
    Client -> Server : Close WebSocket
    Client -> Server: Request Session Report
    Server -> Server : Process Session Report
    Server -> Client : Respond With Session Report
   end
end

end

@enduml
