name: Build CSD Project
run-name: Running Build

on:
  pull_request:
    branches:
      - main

jobs:
  BuildClientAppAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Building Client Application for Android
        run: ./gradlew assembleDebug

  BuildClientAppDesktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Building Client Application for ${{ matrix.os }}
        run: ./gradlew packageDistributionForCurrentOS

  BuildKtor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: "Build Server and Car Demo App With Runtime Dependencies"
        run: ./gradlew buildFatJar