name: Pre-Production

on:
  push:
    branches:
      - main

jobs:
  CreateTag:
    runs-on: ubuntu-latest
    steps:
      - uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GH_TOKEN}}

  BuildClientAppAndroidRel:
    runs-on: ubuntu-latest
    needs: CreateTag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Building Release  Client Application for Android
        run: ./gradlew assemble
      - name: Upload Android Application
        uses: actions/upload-artifact@v4
        with:
          name: android-client
          path: |
            */**/composeApp-release-unsigned.apk
            */**/output-metadata.json

  BuildClientAppDesktopRel:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: CreateTag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Building Release Client Application for ${{ matrix.os }}
        # Actual release job not working
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Desktop Client
        uses: actions/upload-artifact@v4
        with:
          name: desktop-client-${{ matrix.os }}
          path: |
            composeApp/build/compose/binaries/main/

  BuildKtorJar:
    runs-on: ubuntu-latest
    needs: CreateTag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build Server and Car Demo App With Runtime Dependencies
        run: ./gradlew buildFatJar
      - name: Upload Server And Car Client
        uses: actions/upload-artifact@v4
        with:
          name: server-car-artifact
          path: |
            */**/libs/*-all.jar