name: Production
run-name: Release Jobs

on:
  workflow_run:
    workflows: [Pre-Production]
    types: [completed]
    branches:
      - main

jobs:
  DownloadAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: |
           server-car-artifact
           desktop-client-*
          merge-multiple: true
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
