name: Production
run-name: Release Jobs

on:
  workflow_run:
    workflows: [Pre-Production]
    types: [completed]
    branches:
      - main

jobs:
  DownloadAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Tag Value
        id: vars
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          pattern: |
           server-car-artifact
           desktop-client-*
          merge-multiple: true
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create ${{ steps.vars.outputs.tag }} \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes
              --draft
              --notes-from-tag
