name: Production
run-name: Release Jobs

on:
  workflow_run:
    workflows: [Pre-Production]
    types: [completed]
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  DownloadAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GH_TOKEN }}
          merge-multiple: true
          path: artifacts.tar.gz
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create $(git describe --tags $(git rev-list --tags --max-count=1)) \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes \
              --draft
      - name: Upload Artifact To Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release upload $(git describe --tags $(git rev-list --tags --max-count=1)) \
              --repo="$GITHUB_REPOSITORY" \
              --file=artifacts.tar.gz