name: Production
run-name: Release Jobs

on:
  workflow_run:
    workflows: [Pre-Production]
    types: [completed]
    branches:
      - main

jobs:
  DownloadAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: |
           server-car-artifact
           desktop-client-*
          merge-multiple: true
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes
              --draft
              --notes-from-tag
